version: '3.8'
services:
  api-gateway:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - user-service
      - task-service
      - report-service

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    depends_on:
      - dynamodb

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    depends_on:
      - auth-service
      - dynamodb

  task-service:
    build: ./task-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service

  report-service:
    build: ./report-service
    ports:
      - "3004:3004"
    depends_on:
      - task-service

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
